os: linux
dist: bionic
language: java
jdk: openjdk11
stages:
- Tests
- Build
- name: GitHub Release
  if: branch = master
- name: Deploy Heroku
  if: branch = development
jobs:
  include:
  - stage: Tests
    script: "./gradlew clean check"
  - stage: Build
    script: "./gradlew clean build"
  - stage: GitHub Release
    script: "./gradlew clean bootJar"
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      file: build/libs/pizzeria-0.0.1-SNAPSHOT.jar
      skip_cleanup: true
      on:
        branch: master
  - stage: Deploy Heroku
    deploy:
      provider: heroku
      api_key:
        secure: EHupeM87B14iTloShgncqK9vHaWZiAdAhwOM7YO0wKJtKpfaWDFuJ4TckLAL+k0UZ8v5sPJmY5ENUNJC5FOaxVhrurCf+CnrdGV4Q/0e/5H37RlOUgDGvoSHSbCZ0PqNSzpbLeMbqKgRnFCK3302iU+c8KRkhLr+jk7SR1uMWh6JFGnnocZqtcTy2DiM5YeioGbu1619FyDDyeMadCocrnhfvsQa+/FaV0TOZStP2riMZ6o4GuxgJ1XqeQWs3PiKDDMHCkIgk5QzV66sbkr4epuAO3ulBLW5zWWKHY08iecpzogPtZ8x0jeKq0ehd12MJcZe1R/jH/ozUfHmCwuQfYpsdV7SuqbaIbKnimmB3otWHWis69aVsiiN3Af4Mu7Q4RkrifH05NRX5v+Uq7HRLpXHdakaoJAwhps1dr5zihcW5fq9aHetzz03gH8SbTzT6UXmWtiOq9Q2NLJ+ptniybaMZbSVhZjHCW2hAIKeH/0jQhsuWeeTuAp2hYHKC8Ai1Y3hTs2ZigEmba04r7gA0pfAXKhKLCr1kJ8RyXYPAmAczKtPpB3pMjTAdn4zO/Kbr5QcSjAqmHTUv0+Xf5zIz+Gf7RQXAiJbmrEqLeJz3QeQBC6sYyGummMlSU3eOC9QGH/wBCvPmNqEp9p5Inx8edCy95BpgJuODyf6Igug72I=
      app: pizzeria-backend-zpi
      on:
        branch: development
        repo: Burdzi0/Pizzeria-Backend
